### ISSUE TITLE
power cut to electirc funace puts it back at vanilla rate

### ISSUE THREAD

**Issue by hamilton5** [WheteThunger/QuickSmelt#1]
First of all I'm so grateful you took the time to fix the speed issue and even include the electric furnaces. So I hate to bring it up to you, but if you cut the power to an electric furnace and turn it back on it's at vanilla rate. You can click 'turn off' and 'turn on' at the furnace to fix it.

https://i.imgur.com/2lfsZN7.png

**Comment by WheteThunger** [comment]
Thanks for reporting. I'll look into it now.

**Comment by WheteThunger** [comment]
I've pushed the update. It turns out that furnaces ignited by fire had the same issue, which I also fixed.
