### ISSUE TITLE
Meat beeing cooked in the output slot + chicken breast is bugged

### ISSUE THREAD

**Issue by Scrubbyy** [WheteThunger/QuickSmelt#2]
I came a across this issue, that all kind of meat is still beeing cooked in the output slot of, for example, a campfire. This results in the meat to get burned. This only happens with QuickSmelt loaded. Also the chicken breast is kind of "bugged", as soon as it finishes cooking, it spams this into the console: `Creating item with less than 1 amount! (Burnt Chicken)`. And the item count goes on and off as you can see in the video. ([here](https://medal.tv/games/rust/clips/14qYGs2khfOiDl/d1337mvnjJPy?invite=cr-MSxIcXIsMzU0MzI4MDks))

With QuickSmelt beeing unloaded nothing like that occurs.
Also some players managed to create a stack of 2.147.483.303 cooked chicken breast, that might be linked to that issue I stated above.

**Comment by WheteThunger** [comment]
Fixed in v5.1.9. Thanks for reporting!

**Comment by Scrubbyy** [comment]
Just installed the update and saw that wolf meat, bear meat and pork are still beeing cooked in the output slot. Its only these 3 though. Chicken, deer meat and so on works fine.
Thank you for updating it that quick!

**Comment by Scrubbyy** [comment]
**Update: Turns out that all meat types are still beeing cooked in the output slot although it doesnt show the green bar for every type of meat.**

Also a player managed to get a 50 million stack of cooked deer meat again. The problem is I can not reproduce this bug, the players description was like this:
- he took the cooked meat from the campfire into his campfire
- wanted to place it into a box
- the meat was taken from his inventory and "hang" in the air
- he picked it up again and hat kind of an unlimited amount of it

Its really weird, and I have no clue on my own whats going on there, but maybe you know more 😄

**Comment by WheteThunger** [comment]
Was that meat still in the output slots from before you installed the update?

**Comment by Scrubbyy** [comment]
No, I also placed new campfires and barbeques to test it.

**Comment by WheteThunger** [comment]
Ok, should be fixed in v5.1.10.

**Comment by Scrubbyy** [comment]
Yup, tested everything and no burned meat finally.
Thank you!
