### ISSUE TITLE
False false ?

### ISSUE THREAD

**Issue by gabrielcox** [WheteThunger/QuickSmelt#4]
Good work -- thanks for taking over maintenance of this project.

This is simply an academic question -- everything seems to be working fine.

I'm curious about the new "False" object.  Why did you create it? I would expect "regular/Boolean false" was giving you some trouble.
I see onOvenStart and onOvenToggle return it.  Are those events called by something that needs an object rather than Boolean returned?  Do they need anything returned since they're (presumably) fired events?

**Comment by WheteThunger** [comment]
Oxide will implicitly box all hook return values as an object, causing a heap allocation, which will be subsequently discarded and become work for the garbage collector. By using a consistent boxed value up front, no additional allocations are needed. This is simply a performance optimization. This is only applicable to value types such as numbers, enums, booleans, and structs.
